version: '3'
services:
  configuration:
    build: ./Configuration
    ports:
      - "8888:8888"
    networks:
      - dodo-net

  category:
    build: ./Category
    depends_on:
      - configuration
      - db
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - dodo-net

  product:
    build: ./Product
    depends_on:
      - configuration
      - db
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - dodo-net

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dodo
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - dodo-net

networks:
  dodo-net:

