server:
  port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://dpg-d1e1fuemcj7s73bf7af0-a:5432/ecommerce_database_wzx1
    username: ecommerce_database_wzx1_user
    password: wlhHG6LXCirDqKOFqrjZzWWBL0wqVpUF
    driver-class-name: org.postgresql.Driver
